/* Generated By:JavaCC: Do not edit this line. ReaderConstants.java */
package jus.aoo.boole.reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CIRCUIT = 5;
  /** RegularExpression Id. */
  int NUM = 6;
  /** RegularExpression Id. */
  int ID = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int DIESE = 10;
  /** RegularExpression Id. */
  int PARO = 11;
  /** RegularExpression Id. */
  int PARF = 12;
  /** RegularExpression Id. */
  int FLECHE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"circuit\"",
    "<NUM>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\".\"",
    "\"<\"",
    "\"|\"",
    "\";\"",
    "\">\"",
  };

}
